# -*- coding: utf-8 -*-
"""Using Google Gemini API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SzOe2zCkVLyJdPyYwlam08OrCSZTdg97
"""

pip install -q -U google-genai

import pathlib
import textwrap
import google.generativeai as genai

from google.colab import userdata
from IPython.display import Markdown, display

def to_markdown(text):
  text = text.replace('•', '*')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _ :True))

import os
os.environ['GOOGLE_API_KEY'] = "AIzaSyAfJF4KpBt7eBmKlAZN1Rx-054dKhVSiGs"

genai.configure(api_key=os.environ['GOOGLE_API_KEY'])

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = genai.GenerativeModel('gemini-pro')

model



# Commented out IPython magic to ensure Python compatibility.
# %%time
# response = model.generate_content('What is the rules of cricket')

to_markdown(response.text)

import google.generativeai as genai

# Configure the API key for Gemini
# genai.configure(api_key="GEMINI_API_KEY")
genai.configure(api_key=os.environ['GOOGLE_API_KEY'])
# Initialize the GenerativeModel and start a chat
model = genai.GenerativeModel("gemini-1.5-flash")
chat = model.start_chat(
    history=[
        {"role": "user", "parts": "Hello, you are a great text summarizer"},
        {"role": "model", "parts": "Thankyou, glad I am able to help"},
    ]
)

# Example text to summarize
input_text = """
Climate change refers to long-term shifts in temperatures and weather patterns. These changes may be natural, such as through variations in the solar cycle. However, since the 1800s, human activities have been the main driver of climate change, primarily due to burning fossil fuels like coal, oil, and gas. Burning these materials generates greenhouse gas emissions that trap heat in the atmosphere, leading to global warming.
"""

# Request text summarization
response = chat.send_message(f"Summarize the following text:\n\n{input_text}")
print("Summary:")
print(response.text)



